### ISSUE TITLE
Grab image data

### ISSUE THREAD

**Issue by nicolasvahidzein** [vertcitron/vue-avatar-component#2]
Hello, i like your component a lot.

Is it possible to grab the image data?

**Comment by ssouron** [comment]
What do you mean by grab the image data ?


------------------------------
*Stéphane Souron*
------------------------------



Le ven. 10 août 2018 à 10:10, Nicolas Zein <notifications@github.com> a
écrit :

**Comment by nicolasvahidzein** [comment]
The base64 image data used in the avatar.

**Comment by ssouron** [comment]
I can't understand... There is no image provided in the component. If you use the component without the image property it displays a full HTML / CSS div with text, and if the image property is used then the text is replaced by the image you provide yourself. So I can't figure what image data you speak about...
